# Generated by Django 3.0.6 on 2022-09-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libros',
            fields=[
                ('ID_Libro', models.IntegerField(max_length=40, primary_key=True, serialize=False)),
                ('Nombre_Libro', models.CharField(max_length=40)),
                ('Autor', models.CharField(max_length=40)),
                ('Estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='prestamos',
            fields=[
                ('ID_Libro', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ID_User', models.IntegerField(max_length=20)),
                ('Estado', models.CharField(max_length=10)),
                ('Fecha_inicio', models.DateField()),
                ('Fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('ID_User', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre_Usuario', models.CharField(max_length=40)),
                ('Direccion_Usuario', models.CharField(max_length=60)),
            ],
        ),
    ]
