# Generated by Django 3.0.6 on 2022-09-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220924_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='Autor',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='libros',
            name='Estado',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='libros',
            name='Nombre_Libro',
            field=models.CharField(max_length=80),
        ),
    ]
