# Generated by Django 3.0.6 on 2022-09-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220924_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='Estado',
            field=models.CharField(max_length=20),
        ),
    ]
