# Generated by Django 3.0.6 on 2022-09-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220924_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='ID_Libro',
            field=models.PositiveIntegerField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='ID_Libro',
            field=models.PositiveIntegerField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='ID_User',
            field=models.PositiveIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='ID_User',
            field=models.PositiveIntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
